<?php
/**
 * Created by IntelliJ IDEA.
 * User: nikit
 * Date: 15.07.2019
 * Time: 13:14
 */

namespace esas\cmsgate;
/**
 * Все настройки удобнее хранить на стороне bitrix24 и получать их по REST, т.к. в Bitrix могут быть созданы несколько
 * способов оплаты, на одном и том же handler. Поэтому в БД шлюза имеет смысл сохранять только авторизационные данные, а настройки
 * конкретной ПС подтягивать уже по данным заказа
 * @package esas\cmsgate
 */
class ConfigStorageBitrix24Cloud extends ConfigStorageCloud
{
    protected $restPaysystemConfig;

    public function __construct()
    {
        parent::__construct();
        //получаем настройки
        $paymentId = CloudRegistry::getRegistry()->getOrderCacheService()->getSessionOrderCacheSafe()->getOrderData();
        $this->restPaysystemConfig = CmsConnectorBitrix24Cloud::getInstance()->getBitrix24Api()->salePaysystem()->get();
    }

    public function getConstantConfigValue($key)
    {
        switch ($key) {
            case ConfigFields::orderStatusPending():
            case ConfigFields::orderPaymentStatusPending():
                return "cmsgate_pending";
            case ConfigFields::orderStatusPayed():
            case ConfigFields::orderPaymentStatusPayed():
                return "cmsgate_payed";
            case ConfigFields::orderStatusFailed():
            case ConfigFields::orderPaymentStatusFailed():
                return "cmsgate_failed";
            case ConfigFields::orderStatusCanceled():
            case ConfigFields::orderPaymentStatusCanceled():
                return "cmsgate_canceled";
            case ConfigFields::useOrderNumber():
                return true;
            default:
                return null;
        }
    }

    public function getConfig($key)
    {
        return parent::getConfig($key); // TODO: Change the autogenerated stub
    }


    public function createCmsRelatedKey($key) {
        return 'ps_' . $key;
    }
}